avi_config:
  pool:
    - name: portal-staging-pool
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ lookup('env', 'SERVER1') }}"
             type: 'V4'
        - ip:
             addr: "{{ lookup('env', 'SERVER2') }}"
             type: 'V4'
             
  poolgroup:
    - name: Staging-Portal-PG
      members:
        - pool_ref: "/api/pool?name=portal-staging-pool"
          ratio: "{{ lookup('env', 'RATIO') }}"
